language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - sudo pip install codecov

before_script:
  - composer install --dev
  - pear install --alldeps PHP_CodeSniffer
  - phpenv rehash

script:
  - phpunit --coverage-clover build/logs/clover.xml
  - phpcs --standard=PSR2 --ignore=/vendor ./

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - codecov

notifications:
  email:
    - genvaldartem@gmail.com
