language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer install
  - pear install --alldeps PHP_CodeSniffer
  - phpenv rehash
  - phpcs --standard=PSR1 --ignore=/vendor ./

script: phpunit

notifications:
  email:
    - genvaldartem@gmail.com
