language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
    allow_failures:
        - php: hhvm
        
before_install:
  sudo pip install codecov

before_script:
  - composer install --dev

script:
  - phpunit
  
after_success:
  codecov  

notifications:
  email:
    - genvaldartem@gmail.com
