language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
    allow_failures:
        - php: hhvm  

before_script:
  - composer install --dev
  - pear install --alldeps PHP_CodeSniffer
  - phpenv rehash

script:
  - phpunit
  - phpcs --standard=PSR2 --ignore=/vendor ./

notifications:
  email:
    - genvaldartem@gmail.com
